### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]

### ISSUE THREAD

**Issue by pccai** [chenshuai2144/antd-pro-merge-less#26]
INFO 💄  build theme
🔩 less render start!
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFileSync (fs.js:1517:5)
    at loop (G:\SVN2\trunk\HY.WebUI\node_modules\antd-pro-merge-less\index.js:287:12)
    at build (G:\SVN2\trunk\HY.WebUI\node_modules\antd-pro-merge-less\index.js:299:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by LilianShi** [comment]
> ss render start!
> TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
> at Object.writeFileSync (fs.js:1517:5)
> at loop (G:\SVN2\trunk\HY.WebUI\node_modules\antd-pro-merge-less\index.js:287:12)
> at build (G:\SVN2\trunk\HY.WebUI\node_modules\antd-pro-merge-less\index.js:299:5) {
> code: 'ERR_INVALID_ARG_TYPE'

请问解决了吗？楼主动态切换主题如何实现的？"antd": "^4.4.0","ant-design-pro":4.2.0
